spring:
  application:
    name: team4
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

server:
  port: 8080

jwt:
  secret: "routinefit-secret-key-for-jwt-token-generation-2026"
  access-token-expiration: 3600000      # 1시간 (밀리초)
  refresh-token-expiration: 1209600000  # 2주 (밀리초)

openai:
  api:
    key: ""